homogenize_excel_col_names = function(dat){

  dat[[1]] = dat[[1]] |>
    dplyr::reframe(Year = 2015,
              Watercraft_Risk_Assessment_ID = Inspection_ID,
              Station = Station_Name,
              Start_Time = Shift_Start_Time,
              End_Time = Shift_End_Time,
              TimeOfInspection = TimeOfInspection,
              Total_BlowBys = `Blow_By's_(Non-compliant)`,
              Inspection_Date = format(TimeOfInspection,"%Y-%m-%d"),
              Inspection_Hour = stringr::str_extract(TimeOfInspection, "[0-9]{2}(?=:[0-9]{2}:[0-9]{2})"),
              Province_Code = Province_State_Previous_Waterbody,
              Country_Code = dplyr::case_when(Province_Code %in% c("AB","BC","MB",
                                                            "NB","NL","NT",
                                                            "NS","NS","NU",
                                                            "PE","QC","ON",
                                                            "SK","YT") ~ "CAN",
                                       TRUE ~ "USA"),
              WatercraftType = dplyr::case_when(Watercraft_Type == "Other" ~ Other_Watercraft_Type,
                                         Watercraft_Type != "Other" ~ Watercraft_Type),
              Number_Of_People_In_Party = Number_of_People_Interacted_with,
              Previous_AIS_Knowledge_Ind = Previous_Knowledge_of_CDD_AIS,
              Previous_AIS_Knowledge_Source = dplyr::case_when(Source_of_Previous_Knowledge_AIS_CDD != "Other" ~ Source_of_Previous_Knowledge_AIS_CDD,
                                                        Source_of_Previous_Knowledge_AIS_CDD == "Other" ~ Other_Source_of_Knowledge),
              Previous_Inspection_Ind = Has_the_watercraft_been_previously_inspected,
              Previous_Inspection_Days_Count = Days_Since_Previous_Inspection,
              Previous_Inspection_Source_Name = Location_of_Previous_Inspection,
              Previous_Waterbody_1_Name = Previous_Waterbody_1,
              Previous_Waterbody_1_Closest_City = dplyr::case_when(City_State_Province_of_Previous_Waterbody_1 != "Other" ~ stringr::str_extract(City_State_Province_of_Previous_Waterbody_1, "[A-Za-z]*(?= )"),
                                                            City_State_Province_of_Previous_Waterbody_1 == "Other" ~ stringr::str_extract(Other_City_State_Province_of_Previous_waterbody_1, "\\,.*")),
              Previous_Waterbody_1_Province_Or_State = Province_State_Previous_Waterbody,
              Previous_Waterbody_1_Days_Out_Of_Water = Days_out_of_waterbody_1,
              Previous_Waterbody_2_Name = Previous_Waterbody_2,
              Destination_Waterbody_1_Name = Destination_Waterbody_1,
              Destination_Waterbody_1_Closest_City = stringr::str_remove_all(Closest_City_to_Destination_Waterbody,"[A-Z]{2}"),
              Destination_Waterbody_1_Province_Or_State = stringr::str_extract(Closest_City_to_Destination_Waterbody,"[A-Z]{2}"),
              Destination_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Dry") ~ "true",
                                                             stringr::str_detect(Other_Destination_Waterbody, "Dry") ~ "true",
                                                      TRUE ~ "false"),
              Unknown_Destination_Waterbody_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Unknown") ~ "true",
                                                                   stringr::str_detect(Other_Destination_Waterbody, "Unknown") ~ "true",
                                                            TRUE ~ "false"),
              High_Risk_AIS_Ind = dplyr::case_when(Is_the_watercraft_high_risk_for_Dreissenid_mussels_AIS == "yes" ~ "true",
                                            Is_the_watercraft_high_risk_for_Dreissenid_mussels_AIS == "no" ~ "false"),
              Adult_Dressenidae_Found_Ind = dplyr::case_when(Reason_for_High_Risk_Inspection2 == "Dreissenid Mussels Found" ~ "true",
                                                      TRUE ~ "false"),
              Standing_Water_Present_Ind = dplyr::case_when(Reason_for_High_Risk_Inspection2 == "Standing Water" ~ "true",
                                                     TRUE ~ "false"),
              Adult_Dreissenidae_Mussel_Found_Ind = dplyr::case_when(Reason_for_High_Risk_Inspection2 == "Dreissenid Mussels Found" ~ "true",
                                                              TRUE ~ "false"))

  dat[[2]] = dat[[2]] |>
    dplyr::reframe(Year = 2016,
              Watercraft_Risk_Assessment_ID = Inspection_ID,
              Station = Station_Name,
              Start_Time = Shift_Start_Time,
              End_Time = Shift_End_Time,
              Shift_Duration = `Shift_Duration_(hrs)`,
              Motorized_Blow_Bys_Counter = `Blow_By's_(Motorized_Boats)`,
              Non_Motorized_Blow_Bys_Counter = `Blow_By's_(Non-Motorized)`,
              TimeOfInspection = TimeOfInspection,
              Inspection_Date = format(Shift_Date,"%Y-%m-%d"),
              Inspection_Hour = stringr::str_extract(TimeOfInspection, "[0-9]{2}(?=:[0-9]{2}:[0-9]{2})"),
              Province_Code = State_Province_of_Previous_Waterbody,
              Country_Code = dplyr::case_when(Province_Code %in% c("AB","BC","MB",
                                                            "NB","NL","NT",
                                                            "NS","NS","NU",
                                                            "PE","QC","ON",
                                                            "SK","YT") ~ "CAN",
                                       TRUE ~ "USA"),
              WatercraftType = dplyr::case_when(Watercraft_type == "Other" ~ Other_watercraft_type,
                                         Watercraft_type != "Other" ~ Watercraft_type),
              Number_Of_People_In_Party = Number_of_people_in_party,
              Commercially_Hauled_Ind = dplyr::case_when(Is_the_watercraft_equipment_commercially_hauled == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Previous_AIS_Knowledge_Ind = dplyr::case_when(`Previous_knowledge_of_AIS_or_Clean,_Drain,_Dry` == "yes" ~ "true",
                                                     `Previous_knowledge_of_AIS_or_Clean,_Drain,_Dry` == "no" ~ "false"),
              Previous_AIS_Knowledge_Source = dplyr::case_when(`Source_of_AIS_Clean,_Drain,_Dry_Knowledge` != "Other" ~ Other_source_of_AIS_knowledge,
                                                        `Source_of_AIS_Clean,_Drain,_Dry_Knowledge` == "Other" ~ Other_source_of_AIS_knowledge),
              Previous_Inspection_Ind = dplyr::case_when(Previous_inspection == "yes" ~ "true",
                                                  Previous_inspection == "no" ~ "false"),
              Previous_Inspection_Days_Count = Number_of_days_since_previous_inspection,
              Previous_Inspection_Source_Name = Location_of_previous_inspection,
              Previous_Waterbody_1_Name = dplyr::case_when(`Previous_waterbody_(1)` == "Other" ~ Other_waterbody_1,
                                                    `Previous_waterbody_(1)` != "Other" ~ `Previous_waterbody_(1)`),
              Previous_Waterbody_1_Closest_City = dplyr::case_when(Closest_City_to_Previous_Waterbody_1 == "Other" ~ Other_closest_city_to_waterbody_1,
                                                            Closest_City_to_Previous_Waterbody_1 != "Other" ~ Closest_City_to_Previous_Waterbody_1),
              Previous_Waterbody_1_Province_Or_State = State_Province_of_Previous_Waterbody,
              Previous_Waterbody_1_Days_Out_Of_Water = Number_of_days_out_of_waterbody_1,
              Previous_Waterbody_2_Name = dplyr::case_when(`Previous_waterbody_(2)` == "Other" ~ Other_waterbody_2,
                                                    `Previous_waterbody_(2)` != "Other" ~ `Previous_waterbody_(2)`),
              Previous_Waterbody_2_Closest_City = Closest_City_to_Previous_Waterbody_2,
              Previous_Waterbody_2_Province_Or_State = State_Province_of_Previous_Waterbody_2,
              Previous_Waterbody_2_Days_Out_Of_Water = Number_of_days_out_of_waterbody_2,

              Previous_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(`Previous_waterbody_(1)`, "Dry Storage") ~ "true",
                                                   TRUE ~ "false"),
              Unknown_Previous_Water_Body_Ind = dplyr::case_when(stringr::str_detect(`Previous_waterbody_(1)`, "Unknown") ~ "true",
                                                          TRUE ~ "false"),
              Destination_Waterbody_1_Name = dplyr::case_when(Destination_waterbody_1 == "Other" ~ Other_destination_waterbody,
                                                       Destination_waterbody_1 != "Other" ~ Destination_waterbody_1),
              Destination_Waterbody_1_Closest_City = Closest_City_to_Destination_Waterbody,
              Destination_Waterbody_1_Province_Or_State = State_Province_of_Destination_Waterbody,
              Destination_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Destination_waterbody_1, "Dry Storage") ~ "true",
                                                      TRUE ~ "false"),
              Unknown_Destination_Waterbody_Ind = dplyr::case_when(stringr::str_detect(Destination_waterbody_1, "Unknown") ~ "true",
                                                            TRUE ~ "false"),
              High_Risk_Area_Ind = dplyr::case_when(stringr::str_detect(Reason_for_Inspection, "contaminated") ~ "true",
                                             TRUE ~ "false"),
              High_Risk_AIS_Ind = dplyr::case_when(Is_the_watercraft_equipment_high_risk_for_Dreissenid_Mussels_or_AIS == "yes" ~ "true",
                                            Is_the_watercraft_equipment_high_risk_for_Dreissenid_Mussels_or_AIS == "no" ~ "false"),
              Adult_Dressenidae_Found_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid Mussels Found") ~ "true",
                                                      TRUE ~ "false"),
              Standing_Water_Present_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "Standing Water") ~ "true",
                                                     TRUE ~ "false"),
              Adult_Dreissenidae_Mussel_Found_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid Mussels Found") ~ "true",
                                                              TRUE ~ "false"),
              Decontamination_Performed_Ind = dplyr::case_when(is.na(Decontamination_Order_Reference_Number)==F ~ "true",
                                                        TRUE ~ "false"),
              Decontamination_Reference = Decontamination_Order_Reference_Number,
              Decontamination_order_issued_Ind = dplyr::case_when(stringr::str_detect(Actions_Taken, "Decontamination Order Issued") ~ "true",
                                                           TRUE ~ "false"),
              Seal_Number = Tag_Seal_Number,
              Quarantine_Period_Issued_Ind = dplyr::case_when(stringr::str_detect(Actions_Taken, "30 Day Quarantine Order Issued") ~ "true",
                                                       TRUE ~ "false"))

  dat[[3]] = dat[[3]] |>
    dplyr::reframe(Year = 2017,
              Watercraft_Risk_Assessment_ID = Inspection_ID,
              Station = Station_Name,
              Start_Time = shift_start,
              End_Time = Shift_End_Time,
              Shift_Duration = `Shift_duration_(hrs)`,
              Motorized_Blow_Bys_Counter = `Blow_By's_(Motorized_Boats)`,
              Non_Motorized_Blow_Bys_Counter = `Blow_By's_(Non-Motorized)`,
              New_Passport_Issued_Ind = Was_a_passport_issued,
              Passport_Holder_Ind = dplyr::case_when(stringr::str_detect(Passport_number, "[0-9]+") ~ "true",
                                              TRUE ~ "false"),
              Passport_Number = Passport_number,
              TimeOfInspection = TimeOfInspection,
              Inspection_Date = format(Shift_Date,"%Y-%m-%d"),
              Inspection_Hour = format(TimeOfInspection, "%H"),
              Province_Code = State_Province_of_Previous_Waterbody,
              Country_Code = dplyr::case_when(Province_Code %in% c("AB","BC","MB",
                                                            "NB","NL","NT",
                                                            "NS","NS","NU",
                                                            "PE","QC","ON",
                                                            "SK","YT") ~ "CAN",
                                       TRUE ~ "USA"),
              K9_Inspection_Ind = dplyr::case_when(stringr::str_detect(Was_a_K9_inspection_performed, "yes") ~ "true",
                                            TRUE ~ "false"),
              WatercraftType = dplyr::case_when(Watercraft_type == "Other" ~ Other_watercraft_type,
                                         Watercraft_type != "Other" ~ Watercraft_type),
              Number_Of_People_In_Party = Number_of_people_in_party,
              Commercially_Hauled_Ind = dplyr::case_when(Is_the_watercraft_equipment_commercially_hauled == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Previous_AIS_Knowledge_Ind = dplyr::case_when(`Previous_knowledge_of_AIS_or_Clean,_Drain,_Dry` == "yes" ~ "true",
                                                     `Previous_knowledge_of_AIS_or_Clean,_Drain,_Dry` == "no" ~ "false"),
              Previous_AIS_Knowledge_Source = dplyr::case_when(`Source_of_AIS_Clean,_Drain,_Dry_Knowledge` != "Other" ~ Other_source_of_AIS_knowledge,
                                                        `Source_of_AIS_Clean,_Drain,_Dry_Knowledge` == "Other" ~ Other_source_of_AIS_knowledge),
              Previous_Inspection_Ind = dplyr::case_when(Previous_inspection == "yes" ~ "true",
                                                  Previous_inspection == "no" ~ "false"),
              Previous_Inspection_Days_Count = Number_of_days_since_previous_inspection,
              Previous_Inspection_Source_Name = Location_of_previous_inspection,
              Previous_Waterbody_1_Name = dplyr::case_when(`Previous_waterbody_(1)` == "Other" ~ Other_waterbody_1,
                                                    `Previous_waterbody_(1)` != "Other" ~ `Previous_waterbody_(1)`),
              Previous_Waterbody_1_Closest_City = dplyr::case_when(Closest_City_to_Previous_Waterbody_1 == "Other" ~ Other_closest_city_to_waterbody_1,
                                                            Closest_City_to_Previous_Waterbody_1 != "Other" ~ Closest_City_to_Previous_Waterbody_1),
              Previous_Waterbody_1_Province_Or_State = State_Province_of_Previous_Waterbody,
              Previous_Waterbody_1_Days_Out_Of_Water = Number_of_days_out_of_waterbody_1,
              Previous_Waterbody_2_Name = dplyr::case_when(`Previous_waterbody_(2)` == "Other" ~ Other_waterbody_2,
                                                    `Previous_waterbody_(2)` != "Other" ~ `Previous_waterbody_(2)`),
              Previous_Waterbody_2_Closest_City = Closest_City_to_Previous_Waterbody_2,
              Previous_Waterbody_2_Province_Or_State = State_Province_of_Previous_Waterbody_2,
              Previous_Waterbody_2_Days_Out_Of_Water = Number_of_days_out_of_waterbody_2,
              Previous_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(`Previous_waterbody_(1)`, "Dry Storage") ~ "true",
                                                   TRUE ~ "false"),
              Unknown_Previous_Water_Body_Ind = dplyr::case_when(stringr::str_detect(`Previous_waterbody_(1)`, "Unknown") ~ "true",
                                                          TRUE ~ "false"),
              Destination_Waterbody_1_Name = dplyr::case_when(Destination_waterbody_1 == "Other" ~ Other_destination_waterbody,
                                                       Destination_waterbody_1 != "Other" ~ Destination_waterbody_1),
              Destination_Waterbody_1_Closest_City = Closest_City_to_Destination_Waterbody,
              Destination_Waterbody_1_Province_Or_State = State_Province_of_Destination_Waterbody,
              Destination_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Destination_waterbody_1, "Dry [s,S]torage") ~ "true",
                                                      TRUE ~ "false"),
              Unknown_Destination_Waterbody_Ind = dplyr::case_when(stringr::str_detect(Destination_waterbody_1, "Unknown") ~ "true",
                                                            TRUE ~ "false"),
              Aquatic_Plants_Found_Ind = dplyr::case_when(Is_the_watercraft_free_of_any_aquatic_plants == "no" ~ "true",
                                                   stringr::str_detect(Watercraft_Inspection_Outcome, "Aquatic vegetation found") ~ "true",
                                                   TRUE ~ "false"),
              High_Risk_Area_Ind = dplyr::case_when(stringr::str_detect(Reason_for_High_Risk_Inspection, "contaminated") ~ "true",
                                             TRUE ~ "false"),
              High_Risk_AIS_Ind = dplyr::case_when(Is_the_watercraft_equipment_high_risk_for_Dreissenid_mussels_or_AIS == "yes" ~ "true",
                                            Is_the_watercraft_equipment_high_risk_for_Dreissenid_mussels_or_AIS == "no" ~ "false"),
              Adult_Dressenidae_Found_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid mussels and") ~ "true",
                                                      stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid Mussels Only") ~ "true",
                                                      stringr::str_detect(Watercraft_Inspection_Outcome, "No Dreissenid") ~ "false",
                                                      TRUE ~ "false"),
              Standing_Water_Present_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "and standing water") ~ "true",
                                                     stringr::str_detect(Watercraft_Inspection_Outcome, "Standing Water") ~ "true",
                                                     TRUE ~ "false"),
              Adult_Dreissenidae_Mussel_Found_Ind = dplyr::case_when(stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid mussels and") ~ "true",
                                                              stringr::str_detect(Watercraft_Inspection_Outcome, "Dreissenid Mussels Only") ~ "true",
                                                              stringr::str_detect(Watercraft_Inspection_Outcome, "No Dreissenid") ~ "false",
                                                              TRUE ~ "false"),
              Decontamination_Performed_Ind = dplyr::case_when(Was_a_decontamination_performed == "yes" ~ "true",
                                                        TRUE ~ "false"),
              Decontamination_Reference = Record_of_Decontamination_Reference_Number,
              Decontamination_order_issued_Ind = dplyr::case_when(Was_a_decontamination_order_issued == "yes" ~ "true",
                                                           TRUE ~ "false"),
              Decontamination_order_number = Decontamination_Order_Reference_Number,
              Seal_Issued_Ind = dplyr::case_when(Did_you_seal_the_boat == "yes" ~ "true",
                                          TRUE ~ "false"),
              Seal_Number = Tag_Seal_Number,
              Quarantine_Period_Issued_Ind = dplyr::case_when(Was_a_quarantine_period_issued == "yes" ~ "true",
                                                       TRUE ~ "false"))

  dat[[4]] = dat[[4]] |>
    dplyr::reframe(Year = 2018,
              Watercraft_Risk_Assessment_ID = Inspection_ID,
              Station = Station_Name,
              Start_Time = shift_start,
              End_Time = Shift_End_Time,
              Shift_Duration = `Shift_Duration_(Hrs)`,
              Motorized_Blow_Bys_Counter = `Blow_By's_(motorized_boats)`,
              Non_Motorized_Blow_Bys_Counter = `Blow_By's_(Non-motorized)`,
              K9_On_Shift_Ind = K9_On_Shift,
              New_Passport_Issued_Ind = dplyr::case_when(Was_an_AIS_passport_issued == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Passport_Number = AIS_Passport_Number_Issued,
              TimeOfInspection = TimeOfInspection,
              Inspection_Date = format(Shift_Date,"%Y-%m-%d"),
              Inspection_Hour = format(TimeOfInspection, "%H"),
              Province_Code = State_Province_for_Previous_Waterbody_1,
              Country_Code = dplyr::case_when(Province_Code %in% c("AB","BC","MB",
                                                            "NB","NL","NT",
                                                            "NS","NS","NU",
                                                            "PE","QC","ON",
                                                            "SK","YT") ~ "CAN",
                                       TRUE ~ "USA"),
              K9_Inspection_Ind = dplyr::case_when(stringr::str_detect(K9_Inspection, "yes") ~ "true",
                                            TRUE ~ "false"),
              WatercraftType = dplyr::case_when(Watercraft_Type == "Other" ~ Other_Watercraft_Type,
                                         Watercraft_Type != "Other" ~ Watercraft_Type),
              Number_Of_People_In_Party = Total_People_Interacted_with,
              Commercially_Hauled_Ind = dplyr::case_when(Is_the_Watercraft_Commercially_Hauled == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Previous_AIS_Knowledge_Ind = dplyr::case_when(Previous_knowledge_of_CDD_or_AIS == "yes" ~ "true",
                                                     Previous_knowledge_of_CDD_or_AIS == "no" ~ "false"),
              Previous_AIS_Knowledge_Source = dplyr::case_when(Source_of_Previous_Knowledge_of_CDD_AIS != "Other" ~ Other_Source_of_CDD_AIS_knowledge,
                                                        Source_of_Previous_Knowledge_of_CDD_AIS == "Other" ~ Other_Source_of_CDD_AIS_knowledge),
              Previous_Inspection_Ind = dplyr::case_when(Was_the_watercraft_previously_inspected == "yes" ~ "true",
                                                  Was_the_watercraft_previously_inspected == "no" ~ "false"),
              Previous_Inspection_Found_Dressenidae_Mussels = dplyr::case_when(Dreissenid_Mussels_Found_on_Previous_Inspection == "yes" ~ "true",
                                                                        TRUE ~ "false"),
              Previous_Inspection_Source_Name = Location_of_Previous_Inspection,
              Previous_Waterbody_1_Name = dplyr::case_when(Previous_Waterbody_1 == "Other" ~ Other_Previous_Waterbody_1,
                                                    Previous_Waterbody_1 != "Other" ~ Previous_Waterbody_1),
              Previous_Waterbody_1_Closest_City = dplyr::case_when(Closest_City_to_Previous_Waterbody_1 == "Other" ~ Other_Closest_City_Previous_Waterbody_1,
                                                            Closest_City_to_Previous_Waterbody_1 != "Other" ~ Closest_City_to_Previous_Waterbody_1),
              Previous_Waterbody_1_Province_Or_State = State_Province_for_Previous_Waterbody_1,
              Previous_Waterbody_1_Days_Out_Of_Water = `Days_out_of_water_(previous_waterbody1)`,
              Previous_Waterbody_2_Name = dplyr::case_when(Previous_Waterbody_2 == "Other" ~ Other_Previous_Waterbody_2,
                                                    Previous_Waterbody_2 != "Other" ~ Previous_Waterbody_2),
              Previous_Waterbody_2_Closest_City = Closest_City_to_Previous_Waterbody_2,
              Previous_Waterbody_2_Province_Or_State = State_Province_for_Previous_Waterbody_2,
              Previous_Waterbody_2_Days_Out_Of_Water = `Day_out_of_water_(previous_waterbody_2)`,
              Previous_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Previous_Waterbody_1, "Dry Storage") ~ "true",
                                                   TRUE ~ "false"),
              Unknown_Previous_Water_Body_Ind = dplyr::case_when(stringr::str_detect(Previous_Waterbody_1, "Unknown") ~ "true",
                                                          TRUE ~ "false"),
              Destination_Waterbody_1_Name = dplyr::case_when(Destination_Waterbody_1 == "Other" ~ Other_Destination_Waterbody_1,
                                                       Destination_Waterbody_1 != "Other" ~ Destination_Waterbody_1),
              Destination_Waterbody_1_Closest_City = Closest_City_to_Destination_Waterbody,
              Destination_Waterbody_1_Province_Or_State = State_Province_of_Destination_Waterbody,
              Destination_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Dry [s,S]torage") ~ "true",
                                                      TRUE ~ "false"),
              Unknown_Destination_Waterbody_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Unknown") ~ "true",
                                                            TRUE ~ "false"),
              Aquatic_Plants_Found_Ind = dplyr::case_when(Other_inspection_outcomes == "Aquatic plants found" ~ "true",
                                                   TRUE ~ "false"),
              Marine_Mussel_Found_Ind = dplyr::case_when(Other_inspection_outcomes == "Marine mussels found" ~ "true",
                                                  TRUE ~ "false"),
              High_Risk_AIS_Ind = dplyr::case_when(Is_the_watercraft_high_risk_for_AIS_Dreissenid_mussels == "yes" ~ "true",
                                            Is_the_watercraft_high_risk_for_AIS_Dreissenid_mussels == "no" ~ "false"),
              Adult_Dressenidae_Found_Ind = dplyr::case_when(Dreissenid_Mussels_Found...54 == "yes" ~ "true",
                                                      TRUE ~ "false"),
              Standing_Water_Present_Ind = dplyr::case_when(Standing_water_found == "yes" ~ "true",
                                                     TRUE ~ "false"),
              Adult_Dreissenidae_Mussel_Found_Ind = dplyr::case_when(Dreissenid_Mussels_Found...54 == "yes" ~ "true",
                                                              TRUE ~ "false"),
              Adult_Mussels_Location_Name = Location_of_mussels_or_standing_water_found,
              Decontamination_Performed_Ind = dplyr::case_when(Decontamination_Performed == "yes" ~ "true",
                                                        TRUE ~ "false"),
              Decontamination_Reference = Record_of_Decontamination_Number,
              Decontamination_order_issued_Ind = dplyr::case_when(Decontamination_Order_Issued == "yes" ~ "true",
                                                           TRUE ~ "false"),
              Decontamination_order_number = Decontamination_Order_number,
              Seal_Issued_Ind = dplyr::case_when(Was_a_seal_applied_to_the_watercraft == "yes" ~ "true",
                                          TRUE ~ "false"),
              Seal_Number = Seal_tag_number,
              Quarantine_Period_Issued_Ind = dplyr::case_when(Quarantine_period_issued_for_30_day_drying_time == "yes" ~ "true",
                                                       TRUE ~ "false"))

  dat[[5]] = dat[[5]] |>
    #Coalesce columns for watercraft type...
    dplyr::mutate(Single_watercraft_type = dplyr::coalesce(Single_watercraft_type,Watercraft_Type_1)) |>
    dplyr::reframe(Year = 2019,
              Watercraft_Risk_Assessment_ID = Inspection_ID,
              Station = Station_Name,
              Start_Time = shift_start,
              End_Time = Shift_End_Time,
              Shift_Duration = `Shift_Duration_(hrs)`,
              Motorized_Blow_Bys_Counter = `Blow_By_(Motorized_Boats)`,
              Non_Motorized_Blow_Bys_Counter = `Blow_By_(Non-Motorized_Boats)`,
              K9_On_Shift_Ind = K9_on_Shift,
              New_Passport_Issued_Ind = dplyr::case_when(Was_an_AIS_passport_issued == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Passport_Number = AIS_Passport_Number_Issued,
              TimeOfInspection = TimeOfInspection,
              Inspection_Date = format(Shift_Date,"%Y-%m-%d"),
              Inspection_Hour = format(TimeOfInspection, "%H"),
              Province_Code = State_Province_for_Previous_Waterbody_1,
              Country_Code = dplyr::case_when(Province_Code %in% c("AB","BC","MB",
                                                            "NB","NL","NT",
                                                            "NS","NS","NU",
                                                            "PE","QC","ON",
                                                            "SK","YT") ~ "CAN",
                                       TRUE ~ "USA"),
              K9_Inspection_Ind = dplyr::case_when(stringr::str_detect(K9_Inspection, "yes") ~ "true",
                                            TRUE ~ "false"),
              Non_Motorized_Counter = dplyr::case_when(Single_watercraft_type == "Non-motorized / hand launched watercraft" ~ Number_watercraft,TRUE ~ "0"),
              Simple_Counter = dplyr::case_when(Single_watercraft_type == "Simple watercraft" ~ Number_watercraft, TRUE ~ "0"),
              Complex_Counter = dplyr::case_when(Single_watercraft_type == "Complex watercraft" ~ Number_watercraft, TRUE ~ "0"),
              Very_Complex_Counter = dplyr::case_when(Single_watercraft_type == "Very complex watercraft" ~ Number_watercraft, TRUE ~ "0"),
              Number_Of_People_In_Party = Total_People_Interacted_with,
              Commercially_Hauled_Ind = dplyr::case_when(Is_the_Watercraft_Commercially_Hauled == "yes" ~ "true",
                                                  TRUE ~ "false"),
              Previous_AIS_Knowledge_Ind = dplyr::case_when(Previous_knowledge_of_CDD_or_AIS == "yes" ~ "true",
                                                     Previous_knowledge_of_CDD_or_AIS == "no" ~ "false"),
              Previous_AIS_Knowledge_Source = dplyr::case_when(Source_of_Previous_Knowledge_of_CDD_AIS != "Other" ~ Other_Source_of_CDD_AIS_knowledge,
                                                        Source_of_Previous_Knowledge_of_CDD_AIS == "Other" ~ Other_Source_of_CDD_AIS_knowledge),
              Previous_Inspection_Ind = dplyr::case_when(Was_the_watercraft_previously_inspected == "yes" ~ "true",
                                                  Was_the_watercraft_previously_inspected == "no" ~ "false"),
              Previous_Inspection_Found_Dressenidae_Mussels = dplyr::case_when(Dreissenid_Mussels_Found_on_Previous_Inspection == "yes" ~ "true",
                                                                        TRUE ~ "false"),
              Previous_Inspection_Source_Name = Location_of_Previous_Inspection,
              Previous_Waterbody_1_Name = dplyr::case_when(Previous_Waterbody_1 == "Other" ~ Other_Previous_Waterbody_1,
                                                    Previous_Waterbody_1 != "Other" ~ Previous_Waterbody_1),
              Previous_Waterbody_1_Closest_City = dplyr::case_when(Closest_City_to_Previous_Waterbody_1 == "Other" ~ Other_Closest_City_Previous_Waterbody_1,
                                                            Closest_City_to_Previous_Waterbody_1 != "Other" ~ Closest_City_to_Previous_Waterbody_1),
              Previous_Waterbody_1_Province_Or_State = State_Province_for_Previous_Waterbody_1,
              Previous_Waterbody_1_Days_Out_Of_Water = `Days_out_of_water_(previous_waterbody1)`,
              Previous_Waterbody_2_Name = dplyr::case_when(Previous_Waterbody_2 == "Other" ~ Other_Previous_Waterbody_2,
                                                    Previous_Waterbody_2 != "Other" ~ Previous_Waterbody_2),
              Previous_Waterbody_2_Closest_City = Closest_City_to_Previous_Waterbody_2,
              Previous_Waterbody_2_Province_Or_State = State_Province_for_Previous_Waterbody_2,
              Previous_Waterbody_2_Days_Out_Of_Water = `Day_out_of_water_(previous_waterbody_2)`,
              Previous_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Previous_Waterbody_1, "Dry Storage") ~ "true",
                                                   TRUE ~ "false"),
              Unknown_Previous_Water_Body_Ind = dplyr::case_when(stringr::str_detect(Previous_Waterbody_1, "Unknown") ~ "true",
                                                          TRUE ~ "false"),
              Destination_Waterbody_1_Name = dplyr::case_when(Destination_Waterbody_1 == "Other" ~ Other_Destination_Waterbody_1,
                                                       Destination_Waterbody_1 != "Other" ~ Destination_Waterbody_1),
              Destination_Waterbody_1_Closest_City = Closest_City_to_Destination_Waterbody,
              Destination_Waterbody_1_Province_Or_State = State_Province_of_Destination_Waterbody,
              Destination_Dry_Storage_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Dry [s,S]torage") ~ "true",
                                                      TRUE ~ "false"),
              Unknown_Destination_Waterbody_Ind = dplyr::case_when(stringr::str_detect(Destination_Waterbody_1, "Unknown") ~ "true",
                                                            TRUE ~ "false"),
              Aquatic_Plants_Found_Ind = dplyr::case_when(Aquatic_plants_found_on_inspection == "yes" ~ "true",
                                                   TRUE ~ "false"),
              Marine_Mussel_Found_Ind = dplyr::case_when(Other_inspection_outcomes == "Marine mussels found" ~ "true",
                                                  TRUE ~ "false"),
              Marine_Species_Found_Ind = dplyr::case_when(Marine_species_found_on_inspection == "yes" ~ "true",
                                                   TRUE ~ "false"),
              High_Risk_AIS_Ind = dplyr::case_when(Is_the_watercraft_high_risk_for_AIS_Dreissenid_mussels == "yes" ~ "true",
                                            Is_the_watercraft_high_risk_for_AIS_Dreissenid_mussels == "no" ~ "false"),
              Adult_Dressenidae_Found_Ind = dplyr::case_when(Dreissenid_Mussels_Found...62 == "yes" ~ "true",
                                                      TRUE ~ "false"),
              Standing_Water_Present_Ind = dplyr::case_when(Standing_water_found == "yes" ~ "true",
                                                     TRUE ~ "false"),
              Adult_Dreissenidae_Mussel_Found_Ind = dplyr::case_when(Dreissenid_Mussels_Found...62 == "yes" ~ "true",
                                                              TRUE ~ "false"),
              Adult_Mussels_Location_Name = Location_of_mussels_or_standing_water_found,
              Decontamination_Performed_Ind = dplyr::case_when(Decontamination_Performed == "yes" ~ "true",
                                                        TRUE ~ "false"),
              Decontamination_Reference = Record_of_Decontamination_Number,
              Decontamination_order_issued_Ind = dplyr::case_when(Decontamination_Order_Issued == "yes" ~ "true",
                                                           TRUE ~ "false"),
              Decontamination_order_number = Decontamination_Order_number,
              Seal_Issued_Ind = dplyr::case_when(Was_a_seal_applied_to_the_watercraft == "yes" ~ "true",
                                          TRUE ~ "false"),
              Seal_Number = Seal_tag_number,
              Quarantine_Period_Issued_Ind = dplyr::case_when(Quarantine_period_issued_for_30_day_drying_time == "yes" ~ "true",
                                                       TRUE ~ "false"))

  return(dat)
}
